version: "3.2"
services:
  web-api:
    image: wregistry.wemakeprice.com/infracm/web-api:develop
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./app/
        target: /app/app/
        read_only: true
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --explicit-defaults-for-timestamp=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "v3ryv3rys3cr3t"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - type: bind
        source: ./db/docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d/
        read_only: true
      - type: volume
        source: infracm-web-api-db-storage
        target: /var/lib/mysql
    env_file:
      - .env


volumes:
  infracm-web-api-db-storage:
    external: true
