---
# @awx_project
# awx 상에 등록된 프로젝트 명
# @project
# 프로비저닝하는 서비스 이름, 해당 이름을 기준으로 인벤토리 그룹이 지정됨
# {develop, QA, STG, PROD, es_migrate, etc..}
# @profile
# 구성하는 환경
# {dev, qa, stg, prod}
awx_project: develop
project: nd-delivery-api
profile: dev
