-- 1. 테이블 생성 구문 : vipaddr_tb
 CREATE TABLE vipaddr_tb(
  id INT(11) NOT NULL AUTO_INCREMENT,
  vip_addr VARCHAR(20) NOT NULL UNIQUE,
  domain_name VARCHAR(100) NULL,
  create_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  use_yn VARCHAR(10) NOT NULL,
  CONSTRAINT vipaddr_PK PRIMARY KEY(id) 
) CHARACTER SET utf8 COLLATE utf8_general_ci;
